name: Project 5 Workflow

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*.*.*' # Trigger on tags
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract tags, labels for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: obeyeddog/f23cicd-ayroberts
          tags: |
            type=ref,event=branch
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            obeyeddog/f23cicd-ayroberts:latest
          labels: ${{ steps.meta.outputs.labels }}
